### ISSUE TITLE
[FORM] Some suggestions

### ISSUE THREAD

**Issue by proudparrot2** [Math-Study/bunker-v1#12]
**Suggestion/Submission below**
I think that it is looking great so far but I think you could do better so I'm going to give you some suggestions First, make sure that all of the buttons work and that there is a page for them. I see that whenever I  click the calculator option it opens a blank page you probably already knew this but just in case you didn't the app store doesn't work. I like how the website viewer actually works unlike some sites. Overall great site my discord tag is Skullisland#2347 if you want to reach out for me thanks!!!!!

**Comment by Cattn** [comment]
1. I didn't know calculator was broken, thanks for sharing, 2. Yeah app store isn't finished, 3. Thank you!

**Comment by Cattn** [comment]
RIP discord doesn't work
