### ISSUE TITLE
An Auto-Update Feature

### ISSUE THREAD

**Issue by Bro-11** [Math-Study/bunker-v1#2]
So each version of bunker would have a text file named Version.txt with the version number in it. Every time you run bunker it would check the GitHub page and check if the two versions match. If the version is behind, it will bring up an alert to ask if you want to update since there is an update available. If they select no, the alert will disappear until the next time the user opens bunker again. If they select yes, it will get the files from the GitHub page for the most recent version and replace the old files with the new files. 
This may be a little difficult to implement (I haven't learned Javascript yet), but it would certainly be a very neat and modern feature to include and would drastically increase user-friendliness.

**Comment by mathadventure1** [comment]
Very good suggestion, @JavaScythe Has implemented this with bunker v7, but using a server connection, I can look into ways of doing this with github, otherwise we may opt for a server-approach, this probably won't be included in the initial release as we have 2 huge pending features to finish.

**Comment by mathadventure1** [comment]
Also I realized I responded on wrong acc this is Cattn

**Comment by Bro-11** [comment]
Ok, it doesn't have to be with GitHub anyway you can achieve this is fine.

**Comment by JavaScythe** [comment]
i can ez do with github
will work on it now

**Comment by JavaScythe** [comment]
the feature is done!
it can detect updates, download them, then write them to your bunker folder, without re-downloading
now we wait for @Cattn to merge it

**Comment by Cattn** [comment]
Merged
